# Generated by Django 3.2.4 on 2021-06-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_subscribtionservice_subscribers'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribtionservice',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
